<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>TP de Biométrie Semestre 5 - 4&nbsp; Analyse de cohortes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-DynamicSystems.html" rel="next">
<link href="./03-TwoSampleTests.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Pas de résultats",
    "search-matching-documents-text": "documents trouvés",
    "search-copy-link-title": "Copier le lien vers la recherche",
    "search-hide-matches-text": "Cacher les correspondances additionnelles",
    "search-more-match-text": "correspondance de plus dans ce document",
    "search-more-matches-text": "correspondances de plus dans ce document",
    "search-clear-button-title": "Effacer",
    "search-detached-cancel-button-title": "Annuler",
    "search-submit-button-title": "Envoyer",
    "search-label": "Recherche"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-Cohortes.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Analyse de cohortes</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title"><span id="sec-cohortes" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Analyse de cohortes</span></span></h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">TP de Biométrie<br> Semestre 5<br></a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/besibo/BiometrieS5" rel="" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./TP-de-Biométrie-br--Semestre-5-br-.pdf" rel="" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Recherche"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-OneSampleTests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Comparaison de la moyenne d’une population à une valeur théorique</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-TwoSamplePairedTests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Comparaison de moyennes : deux échantillons appariés</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-TwoSampleTests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Comparaison de moyennes : deux échantillons indépendants</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-Cohortes.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Analyse de cohortes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-DynamicSystems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Systèmes dynamiques</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table des matières</h2>
   
  <ul>
  <li><a href="#objectifs" id="toc-objectifs" class="nav-link active" data-scroll-target="#objectifs"><span class="header-section-number">4.1</span> Objectifs</a></li>
  <li><a href="#sec-pres" id="toc-sec-pres" class="nav-link" data-scroll-target="#sec-pres"><span class="header-section-number">4.2</span> Présentation de l’étude</a></li>
  <li><a href="#avant-de-vous-lancer" id="toc-avant-de-vous-lancer" class="nav-link" data-scroll-target="#avant-de-vous-lancer"><span class="header-section-number">4.3</span> Avant de vous lancer…</a></li>
  <li><a href="#les-étapes-de-lanalyse" id="toc-les-étapes-de-lanalyse" class="nav-link" data-scroll-target="#les-étapes-de-lanalyse"><span class="header-section-number">4.4</span> Les étapes de l’analyse</a></li>
  <li><a href="#sélection-des-données-dune-date-spécifique" id="toc-sélection-des-données-dune-date-spécifique" class="nav-link" data-scroll-target="#sélection-des-données-dune-date-spécifique"><span class="header-section-number">4.5</span> Sélection des données d’une date spécifique</a></li>
  <li><a href="#structure-démographique-instantanée" id="toc-structure-démographique-instantanée" class="nav-link" data-scroll-target="#structure-démographique-instantanée"><span class="header-section-number">4.6</span> Structure démographique instantanée</a></li>
  <li><a href="#décomposition-polymodale" id="toc-décomposition-polymodale" class="nav-link" data-scroll-target="#décomposition-polymodale"><span class="header-section-number">4.7</span> Décomposition polymodale</a>
  <ul class="collapse">
  <li><a href="#principe-et-étapes" id="toc-principe-et-étapes" class="nav-link" data-scroll-target="#principe-et-étapes"><span class="header-section-number">4.7.1</span> Principe et étapes</a></li>
  <li><a href="#création-du-premier-objet" id="toc-création-du-premier-objet" class="nav-link" data-scroll-target="#création-du-premier-objet"><span class="header-section-number">4.7.2</span> Création du premier objet</a></li>
  <li><a href="#création-du-deuxième-objet" id="toc-création-du-deuxième-objet" class="nav-link" data-scroll-target="#création-du-deuxième-objet"><span class="header-section-number">4.7.3</span> Création du deuxième objet</a></li>
  <li><a href="#ajustement-des-lois-normales-aux-données" id="toc-ajustement-des-lois-normales-aux-données" class="nav-link" data-scroll-target="#ajustement-des-lois-normales-aux-données"><span class="header-section-number">4.7.4</span> Ajustement des lois Normales aux données</a></li>
  <li><a href="#et-en-cas-de-message-derreur" id="toc-et-en-cas-de-message-derreur" class="nav-link" data-scroll-target="#et-en-cas-de-message-derreur"><span class="header-section-number">4.7.5</span> Et en cas de message d’erreur ?</a></li>
  </ul></li>
  <li><a href="#taille-moyenne-et-abondance-des-cohortes" id="toc-taille-moyenne-et-abondance-des-cohortes" class="nav-link" data-scroll-target="#taille-moyenne-et-abondance-des-cohortes"><span class="header-section-number">4.8</span> Taille moyenne et abondance des cohortes</a></li>
  <li><a href="#tableau-et-mise-en-forme-des-données" id="toc-tableau-et-mise-en-forme-des-données" class="nav-link" data-scroll-target="#tableau-et-mise-en-forme-des-données"><span class="header-section-number">4.9</span> Tableau et mise en forme des données</a></li>
  <li><a href="#courbe-de-croissance" id="toc-courbe-de-croissance" class="nav-link" data-scroll-target="#courbe-de-croissance"><span class="header-section-number">4.10</span> Courbe de croissance</a></li>
  <li><a href="#courbe-de-survie" id="toc-courbe-de-survie" class="nav-link" data-scroll-target="#courbe-de-survie"><span class="header-section-number">4.11</span> Courbe de survie</a></li>
  <li><a href="#courbe-dallen" id="toc-courbe-dallen" class="nav-link" data-scroll-target="#courbe-dallen"><span class="header-section-number">4.12</span> Courbe d’Allen</a></li>
  <li><a href="#relation-allométrique" id="toc-relation-allométrique" class="nav-link" data-scroll-target="#relation-allométrique"><span class="header-section-number">4.13</span> Relation allométrique</a></li>
  <li><a href="#à-vous-de-jouer" id="toc-à-vous-de-jouer" class="nav-link" data-scroll-target="#à-vous-de-jouer"><span class="header-section-number">4.14</span> À vous de jouer !</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block page-columns page-full" id="quarto-document-content">




<section id="objectifs" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="objectifs"><span class="header-section-number">4.1</span> Objectifs</h2>
<p>Cette section doit permettre d’illustrer la partie du cours de Population Dynamics de l’EC “Fonctionnement des écosystèmes” consacrée à l’analyse des cohortes. Vous utiliserez les tailes corporelles d’individus échantillonnés sur le terrain à plusieurs dates pour :</p>
<ol type="1">
<li>Produire la structure démographique instantanée de la population pour chaque date d’échantillonnage</li>
<li>Réaliser la décomposition polymodale pour identifier les cohortes à chaque date d’échantillonnage</li>
<li>Créer une courbe de croissance et une courbe de mortalité</li>
<li>Utiliser une relation allométrique pour passer de la taille des individus à leur masse</li>
<li>Produire la courbe d’Allen</li>
</ol>
<p>Vous devrez en premier lieu importer les données fournies dans un fichier Excel et vous assurer qu’elles sont dans un format permettant les analyses et représentations graphiques.</p>
</section>
<section id="sec-pres" class="level2 page-columns page-full" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="sec-pres"><span class="header-section-number">4.2</span> Présentation de l’étude</h2>
<p>Le suivi démographique des populations animales est extrêmement fréquent dans le domaine de l’écologie. Le suivi des populations naturelles est particulièrement pertinent dans un contexte de conservation, pour réaliser des études d’impact ou pour mesurer l’évolution de la biodiversité.</p>
<p>Ici, une population de gastéropodes <em>Nassarius reticulatus</em> (la nasse réticulée) a été suivie pendant 5 ans. Deux sessions d’échantillonnage ont été organisées chaque année depuis 2010 : la première a été réalisée en mars, juste après le recrutement des juvéniles, et la seconde a été réalisée 6 mois plus tard, en septembre. Tous les échantillons ont été collectés au même endroit, selon la même méthode (collecte systématique de tous les individus présents à l’intérieur de 10 quadrats positionnés aléatoirement dans la zone d’étude), lors d’une marée basse de fort coefficient (marées de printemps et d’automne). Les individus échantillonnés ont été mesurés sur place, de la base, à l’apex de la coquille (voir <a href="#fig-nasse">Figure&nbsp;<span class="quarto-unresolved-ref">fig-nasse</span></a>) à l’aide d’un pied à coulisse (précision : centième de millimètre) et relâchés sur place.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div id="fig-nasse" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/Nassarius.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;4.1: Coquille de nasse réticulée <em>Nassarius reticulatus</em> (Linnaeus, 1758)</figcaption>
</figure>
</div>
</div></div><p>L’espèce étudiée présente les caractéristiques suivantes :</p>
<ul>
<li>Les individus ont une durée de vie de 5 ans en moyenne.</li>
<li>Les plus grand individus peuvent atteindre une taille de plus de 40 millimètres.</li>
<li>Il n’y a qu’une seule période de reproduction chaque année. Il n’y a donc qu’un unique recrutement chaque année, au tout début du mois de mars.</li>
</ul>
<p>Des travaux antérieurs réalisés au laboratoire ont montré que la taille et la masse des individus étaient liées par la relation allométrique suivante :</p>
<p><span class="math display">\[w = 0.0013 \cdot l^{2.3}\]</span></p>
<p>avec <span class="math inline">\(w\)</span>, la masse en grammes et <span class="math inline">\(l\)</span> la longueur des coquilles en millimètres.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Objectif principal
</div>
</div>
<div class="callout-body-container callout-body">
<p>L’objectif principal de cette étude est de produire la courbe d’Allen d’une cohorte de cette populations. Cette courbe sera utilisée pour déterminer des gains et des pertes de biomasses au sein de l’écosystème étudié. Les étapes nécessaires à la production de cette courbe sont présentées ci-dessous.</p>
</div>
</div>
</section>
<section id="avant-de-vous-lancer" class="level2 page-columns page-full" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="avant-de-vous-lancer"><span class="header-section-number">4.3</span> Avant de vous lancer…</h2>
<p>Pour travailler dans de bonnes conditions, vous aurez absolument besoin de travailler dans un script et à l’intérieur d’un <code>Rproject</code>. Si vous ne savez plus comment faire, reportez-vous aux chapitrex correspondants du livre en ligne de Biométrie du semestre 3 : <a href="https://besibo.github.io/BiometrieS3/01-R-basics.html#sec-script">au sujet des scripts</a> et <a href="https://besibo.github.io/BiometrieS3/01-R-basics.html#les-projets-ou-rprojects">au sujet des <code>Rprojects</code></a>. Vous devrez notamment (liste non exhaustive !) :</p>
<ol type="1">
<li>Créer un nouveau script (nommez-le <code>Nasses.R</code>)</li>
<li>Télécharger (si besoin) et charger quelques packages (voir plus bas)</li>
<li>Télécharger dans votre répertoire de travail le fichier <a href="data/Nassarius.csv" download="">Nassarius.csv</a></li>
<li>Importer dans <code>RStudio</code> les données du fichier <code>Nassarius.csv</code></li>
</ol>
<p>Pour cette section, vous aurez besoin des packages suivants :</p>
<ul>
<li><code>tidyverse</code> : pour manipuler les données et faire des graphiques <span class="citation" data-cites="tidyverse2019">(<a href="#ref-tidyverse2019" role="doc-biblioref">Wickham et al. 2019</a>)</span></li>
<li><code>mixdist</code> : pour effectuer les décompositions polymodales <span class="citation" data-cites="R-mixdist">(<a href="#ref-R-mixdist" role="doc-biblioref">Macdonald et Juan Du 2018</a>)</span></li>
</ul>
<p>Si vous ne savez plus comment installer et charger des packages en mémoire, reportez-vous au chapitre correspondant du <a href="https://besibo.github.io/BiometrieS3/01-R-basics.html#sec-packages">livre en ligne de Biométrie du semestre 3</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mixdist)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Pour importer les données, utilisez l’assistant d’importation de <code>RStudio</code>. Notez que :</p>
<ul>
<li>Les colonnes sont séparées par des tabulations</li>
<li>Le symbole utilisé pour les décimales dans le fichier <code>Nassarius.csv</code> est la virgule</li>
</ul>
<p>Vous devrez donc spécifier correctement ces éléments pour pouvoir importer le fichier dans le logiciel. Si vous ne savez plus comment faire, reportez-vous au chapitre correspondant du <a href="https://besibo.github.io/BiometrieS3/04-DataWrangling.html#plaintext">livre en ligne de Biométrie du semestre 3</a>.</p>
<p>Si l’importation s’est déroulée normalement, vous devriez maintenant disposer de l’objet nommé <code>Nassarius</code> suivant :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>Nassarius</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,710 × 2
    size date    
   &lt;dbl&gt; &lt;chr&gt;   
 1  4.8  march-10
 2  3    march-10
 3  5.56 march-10
 4  3.74 march-10
 5  4.1  march-10
 6  2.21 march-10
 7  2.75 march-10
 8  3.18 march-10
 9  2.56 march-10
10  4.36 march-10
# ℹ 3,700 more rows</code></pre>
</div>
</div>
<p>Et la commande suivante devrait produire exactement ces résultats :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>Nassarius <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(date)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   date         n
   &lt;chr&gt;    &lt;int&gt;
 1 march-10   468
 2 march-11   481
 3 march-12   460
 4 march-13   468
 5 march-14   487
 6 sept-10    268
 7 sept-11    276
 8 sept-12    265
 9 sept-13    258
10 sept-14    279</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>%&gt;%</code> : le pipe est un opérateur spécial qui prend l’objet situé à gauche et le transmets à la fonction placée à droite, en guise de premier argument. P. ex. : <code>Nassarius %&gt;% count(date)</code> est équivalent à <code>count(Nassarius, date)</code><br>
<br> <code>count()</code> : compte le nombre d’occurrences de chaque valeur possible (ou niveau/modalité) d’une variable catégorielle (ou facteur).</p>
</div></div></section>
<section id="les-étapes-de-lanalyse" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="les-étapes-de-lanalyse"><span class="header-section-number">4.4</span> Les étapes de l’analyse</h2>
<p>Pour produire une courbe d’Allen, de nombreuses étapes sont nécessaires. Vous devrez :</p>
<ol type="1">
<li>Produire la <em>structure démographique instantanée</em> de la population à chaque date d’échantillonnage</li>
<li>Réaliser la <em>décomposition polymodale</em> pour identifier les cohortes présentes dans la population à chaque date d’échantillonnage.</li>
<li>Déterminer la taille moyenne de la coquille des individus de la cohorte d’intérêt, à chaque date d’échantillonnage, pour produire la <em>courbe de croissance</em></li>
<li>Déterminer l’abondance des individus de la cohorte d’intérêt, à chaque date d’échantillonnage, pour produire la <em>courbe de survie</em></li>
</ol>
<p>Je vais présenter ci-dessous les étapes de cette procédure <strong>pour une unique date d’échantillonnage</strong> : march 2010. Vous devrez reproduire ces étapes pour les 9 autres dates d’échantillonnage.</p>
</section>
<section id="sélection-des-données-dune-date-spécifique" class="level2 page-columns page-full" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="sélection-des-données-dune-date-spécifique"><span class="header-section-number">4.5</span> Sélection des données d’une date spécifique</h2>
<p>Notre jeu de données <code>Nassrisu</code> contient 2 colonnes : la première contient les dates d’échantillonnage et la seconde les tailles individuelles en millimètres. La première étape consiste à créer un nouvel objet (nous le nommerons <code>Nas_01</code>) qui contiendra uniquement les données collectées lors de la toute première session d’échantillonnage de mars 2010. Vous devriez déjà savoir comment utiliser la fonction <code>filter()</code> pour le faire :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>Nas_01 <span class="ot">&lt;-</span> Nassarius <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(date <span class="sc">==</span> <span class="st">"march-10"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>Nas_01</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 468 × 2
    size date    
   &lt;dbl&gt; &lt;chr&gt;   
 1  4.8  march-10
 2  3    march-10
 3  5.56 march-10
 4  3.74 march-10
 5  4.1  march-10
 6  2.21 march-10
 7  2.75 march-10
 8  3.18 march-10
 9  2.56 march-10
10  4.36 march-10
# ℹ 458 more rows</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>filter()</code> : permet de filtrer les lignes d’un tableau (ici <code>Nassarius</code>) pour ne conserver que celles qui remplissent une condition spécifiée par l’utilisateur (ici <code>date == "march_10"</code>)</p>
</div></div><div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(Nassarius)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3710    2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(Nas_01)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 468   2</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>dim()</code> : Affiche le nombre de lignes et de colonnes d’un tableau.</p>
</div></div><p>Comme nous pouvons le constater, on passe du tableau original <code>Nasarius</code> contenant 3710 lignes à un nouveau tableau <code>Nas_01</code> qui en contient seulement 468.</p>
</section>
<section id="structure-démographique-instantanée" class="level2 page-columns page-full" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="structure-démographique-instantanée"><span class="header-section-number">4.6</span> Structure démographique instantanée</h2>
<p>Maintenant que nous disposons d’une table <code>Nas_01</code> qui contient uniquement la taille des individus collectés en mars 2010, il nous faut visualiser la structure démographique instantanée afin de déterminer combien de cohortes étaient présentes dans la population à cette date. La structure démographique instantanée est ici simplement un histogramme présentant la distribution des tailles individuelles. Nous allons donc placer la taille des individus sur l’axe des <code>x</code> en guise de descripteur individuel, et sur l’axe des <code>y</code>, <code>RStudio</code> placera automatiquement l’abondance pour chaque classe de taille en guise de descripteur populationel.</p>
<div class="cell page-columns page-full">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>Nas_01 <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> size)) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display page-columns page-full">
<div id="fig-histo1" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="04-Cohortes_files/figure-html/fig-histo1-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption margin-caption">Figure&nbsp;4.2: Structure démographique instantanée</figcaption>
</figure>
</div>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>ggplot()</code> : crée un graphique<br>
<br> <code>aes()</code> : associe une variable d’un jeu de données à une caractéristique esthétique d’un graphique (p.&nbsp;ex. la position le long de l’axe des <code>x</code> ou des <code>y</code>, la couleur, la forme, la taille, etc.)<br>
<br> <code>geom_histogram()</code> : ajoute un objet géométrique de type histogramme à une graphique produit par <code>ggplot()</code></p>
</div></div><p>Notez le message d’avertissement qui s’affiche quand vous produisez cet histogramme. Il indique que <code>R</code> a choisi pour nous le nombre de classes de tailles. Par défaut, il crée 30 classes, mais nous indique que ce n’est certainement pas le meilleur choix. Nous allons donc devoir créer nous même manuellement les classes de tailles pour (i) identifier les cohortes présentes dans la population et (ii) fixer des classes identiques que nous utiliserons pour toutes les autres dates d’échantillonnage et qui rendront les comparaisons plus aisées.</p>
<p>Puisque les individus de cette espèce peuvent atteindre une taille de 40 millimètres environ, nous allons définir des classes de tailles tous les millimètres. On peut faire ça simplement en créant un vecteur qui contient les limites des classes de tailles que l’on souhaite :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul de la taille maximale observée</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>taille_max <span class="ot">&lt;-</span> <span class="fu">max</span>(Nassarius<span class="sc">$</span>size, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>taille_max</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 41.33</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>max()</code> : affiche la valeur maximale contenue dans un vecteur</p>
</div></div><div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Définition des limites des classes de tailles</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>limites <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span>(taille_max <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>limites</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
[26] 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>:</code> : l’opérateur “deux points” permet de créer des suites d’entiers</p>
</div></div><p>L’objet <code>limites</code> contient les limites des classes de tailles que nous utiliserons pour produire les structures démographiques instantanées, pour chaque date d’échantillonnage, et pas seulement pour mars 2010. C’est la raison pour nous avons utilisé <code>max(Nassarius$size) +1</code> : cette syntaxe nous assure que nos classes de tailles recouvrent bien la taille de tous les individus échantillonnés au cours des 5 années d’études. Ainsi, nous pourrons utiliser les mêmes classes de tailles pour toutes les dates.</p>
<p>Maintenant, on peut utiliser le vecteur <code>limites</code> comme argument de la fonction <code>geom_histogram()</code>. On modifie aussi les couleurs des barres de l’histogramme pour mieux visualiser les classes :</p>
<div class="cell page-columns page-full">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>Nas_01 <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> size)) <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">breaks =</span> limites, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display page-columns page-full">
<div id="fig-histo2" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="04-Cohortes_files/figure-html/fig-histo2-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption margin-caption">Figure&nbsp;4.3: Structure démographique instantanée utilisable pour la décomposition polymodale</figcaption>
</figure>
</div>
</div>
</div>
<p>Cette structure démographique instantanée (<a href="#fig-histo2">Figure&nbsp;<span class="quarto-unresolved-ref">fig-histo2</span></a>) fait apparaître 5 cohortes, bien que la plus âgée soit à peine visible. Les pics, ou modes, sont situés autour de 4, 9, 17, 30 et 34 millimètres. Ces valeurs approximatives sont importantes car nous les utiliserons pour réaliser la décomposition polymodale.</p>
</section>
<section id="décomposition-polymodale" class="level2 page-columns page-full" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="décomposition-polymodale"><span class="header-section-number">4.7</span> Décomposition polymodale</h2>
<section id="principe-et-étapes" class="level3 page-columns page-full" data-number="4.7.1">
<h3 data-number="4.7.1" class="anchored" data-anchor-id="principe-et-étapes"><span class="header-section-number">4.7.1</span> Principe et étapes</h3>
<p>Effectuer une décomposition polymodale revient à tenter d’ajuster une distribution Normale à chaque cohorte de la population. Puisque nous avons identifié 5 cohortes dans la population en mars 2010, il nous faut identifier 5 distribution Normales distinctes dont la somme reproduira le plus fidèlement possible la structure démographique instantanée observée. Plusieurs étapes sont requises pour y parvenir.</p>
<p>Nous allons utiliser le package <code>mixdist</code>, que vous devez avoir déjà installé et chargé en mémoire. Ce package fournit plusieurs fonctions relativement simples d’utilisation et qui permettent d’ajuster des distributions Normales à une distribution observée (notre structure démographique instantanée).</p>
<p>La fonction du package <code>mixdist</code> qui nous permettra de réaliser la décomposition polymodale est la fonction <code>mix()</code>. Son fichier d’aide nous indique que pour fonctionner correctement, il faut lui fournir plusieurs choses :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>?<span class="fu">mix</span>()</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>?</code> : l’opérateur “point d’interrogation” suivi du nom d’une fonction, permet d’ouvrir le fichier d’aide de cette fonction.</p>
</div></div><p>Les deux premiers arguments de la fonction <code>mix()</code> ne possèdent pas de valeur par défaut. Nous devons donc spécifier nous même ces deux arguments :</p>
<ol type="1">
<li>Le premier s’appelle <code>mixdat</code>. Il doit obligatoirement s’agir d’un tableau de données (<code>data.frame</code> ou <code>tibble</code>) contenant 2 colonnes. La première colonne doit contenir les limites supérieures des classes de tailles de notre structure démographique instantanée. Le dernier élément de cette colonne doit être “ouvert” : il doit être fixé à <span class="math inline">\(+\infty\)</span>. La seconde colonne doit contenir les abondances pour chaque classe de taille de la structure démographique instantanée. Nous allons voir juste après comment créer cet objet <code>mixdat</code>.</li>
<li>Le second argument s’appelle <code>mixpar</code>. Là encore, il s’agit d’un tableau de données. Il doit contenir des valeurs approchées pour les paramètres des distributions Normales que nous souhaitons ajuster à chacune de nos 5 cohortes. Chaque distribution Normale possède 2 paramètres : la moyenne (qui correspond à la position du pic sur l’axe des <code>x</code> d’un histogramme) et l’écart-type (qui correspond à l’étalement de la courbe en cloche, c’est-à-dire à la dispersion des données de part et d’autre de la moyenne). Là encore, nous verrons plus bas comment créer cet objet.</li>
</ol>
</section>
<section id="création-du-premier-objet" class="level3 page-columns page-full" data-number="4.7.2">
<h3 data-number="4.7.2" class="anchored" data-anchor-id="création-du-premier-objet"><span class="header-section-number">4.7.2</span> Création du premier objet</h3>
<p>Pour créer le premier tableau qui sera utilisé comme argument <code>mixdat</code> de la fonction <code>mix()</code>, nous allons nous servir de la fonction <code>mixgroup()</code> du package <code>mixdist</code>. Elle est très simple `a utiliser puisqu’elle n’a besoin que de 2 arguments :</p>
<ol type="1">
<li>Un vecteur de données (ici, la taille de tous les individus échantillonnés en mars 2010)</li>
<li>La liste des valeurs correspondant aux limites des classes de tailles de la structure démographique instantanée. Nous disposons déjà de cet objet puisque nous l’avons créé plus tôt : c’est le vecteur <code>limites</code></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>mix_01 <span class="ot">&lt;-</span> <span class="fu">mixgroup</span>(Nas_01<span class="sc">$</span>size, <span class="at">breaks =</span> limites)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(mix_01)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "mixdata"    "data.frame"</code></pre>
</div>
</div>
<p>L’objet <code>mix_01</code> que nous venons de créer est donc un <code>data.frame</code>, mais c’est aussi un objet de classe <code>mixdata</code> que nous utiliserons en guise de premier argument de la fonction <code>mix()</code>. Pour afficher son contenu, il suffit comme toujours de taper son nom :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>mix_01</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     X count
1    1     1
2    2     6
3    3    39
4    4    70
5    5    69
6    6    30
7    7    19
8    8    23
9    9    26
10  10    33
11  11    19
12  12     7
13  13     2
14  14     1
15  15     4
16  16     5
17  17    10
18  18    15
19  19     7
20  20    13
21  21     6
22  22     5
23  23     2
24  24     1
25  25     4
26  26     4
27  27     6
28  28     2
29  29     7
30  30     8
31  31     3
32  32     4
33  33     3
34  34     4
35  35     3
36  36     1
37  37     2
38  38     2
39  39     2
40  40     0
41  41     0
42 Inf     0</code></pre>
</div>
</div>
<p>Notez que la dernière ligne de <code>mix_01</code> correspond à la catégorie [42 mm ; <span class="math inline">\(+\infty\)</span>[. Pour vérifier que nous n’avons pas fait d’erreur, on peut faire une représentation graphique de cet objet particulier avec la fonction <code>plot()</code> :</p>
<div class="cell page-columns page-full">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mix_01, <span class="at">xlab =</span> <span class="st">"Size (mm)"</span>, <span class="at">ylab =</span> <span class="st">"Probability"</span>)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display page-columns page-full">
<div id="fig-mixplot" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="04-Cohortes_files/figure-html/fig-mixplot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption margin-caption">Figure&nbsp;4.4: Le contenu de <code>mix_01</code> correspond exactement à la structure démographique instantanée de mars 2010. La ligne bleue est le contour de la structure démographique instantanée, qui devra être approchée par la superposition de 5 courbes Normales correspondant au 5 cohortes qui composent la population en mars 2010</figcaption>
</figure>
</div>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>plot()</code> : fonction générique permettant de produire des graphiques sans <code>ggplot2</code>. La forme du résultat dépendra de la classe de l’objet utilisé comme argument.</p>
</div></div><p>Au final, l’objet <code>mix_01</code> est simplement la structure démographique instantanée de mars 2010, présentée dans un format qui sera compris par la fonction <code>mix()</code> que nous utiliserons pour effectuer la décomposition polymodale.</p>
</section>
<section id="création-du-deuxième-objet" class="level3 page-columns page-full" data-number="4.7.3">
<h3 data-number="4.7.3" class="anchored" data-anchor-id="création-du-deuxième-objet"><span class="header-section-number">4.7.3</span> Création du deuxième objet</h3>
<p>Pour créer le second <code>data.frame()</code> dont la fonction <code>mix()</code> aura besoin, nous allons utiliser une autre fonction du package <code>mixdist</code> : la fonction <code>mixparam()</code>. Cette fonction prend au minimum 2 arguments :</p>
<ol type="1">
<li><code>mu</code> : un vecteur qui contient la position approximative des modes (ou pics) de chaque cohorte. Si nous avons 5 cohortes à identifier, il faudra fournir 5 valeurs pour <code>mu</code>. Pour mars 2010, nous utiliserons les valeurs présentées plus au, au niveau de la <a href="#fig-histo2">Figure&nbsp;<span class="quarto-unresolved-ref">fig-histo2</span></a> (4, 9, 17, 30 et 34 millimètres). Ces valeurs changeront pour chaque date d’échantillonnage et il faudra donc examiner attentivement les structures démographiques instantanées de chaque échantillonnage pour les déterminer. J’insiste sur le fait que la position des pics peut être approximative, mais qu’elle ne doit malgré tout pas être trop éloignée des vraies valeurs.</li>
<li><code>sigma</code> : un vecteur qui contient la valeur approchée de l’écart-type de chaque cohorte. L’écart-type d’une cohorte correspond à l’étalement des tailles de part et d’autres de la moyenne de la cohorte. C’est ce que nous avons appelé “polymorphisme” dans le cours de dynamique des populations, puisque cet étalement représente des performances de croissance variables pour des individus qui sont tous nés approximativement en même temps. Là encore, il faut fournir autant de valeurs que nous avons de cohortes (soit 5 pour mars 2010). Puisque nous n’avons pas d’idée précise d’ordre de grandeur pour ces écarts-types, nous utiliserons la valeur <code>1</code> pour chaque cohorte.</li>
</ol>
<p>Ainsi, on obtient le second <code>data.frame</code> ainsi :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>param_01 <span class="ot">&lt;-</span> <span class="fu">mixparam</span>(<span class="at">mu =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">9</span>, <span class="dv">17</span>, <span class="dv">30</span>, <span class="dv">34</span>),</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">sigma =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>param_01</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   pi mu sigma
1 0.2  4     1
2 0.2  9     1
3 0.2 17     1
4 0.2 30     1
5 0.2 34     1</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>mixparam()</code> : fonction qui crée un <code>data.frame</code> dans lequel chaque ligne contient les caractéristiques approchées d’une cohorte de la population échantillonnée<br>
<br> <code>c()</code> : fonction qui permet de créer un vecteur, donc une collection d’éléments qui sont tous du même type (ici, des valeurs numériques).</p>
</div></div><p>La première colonne de ce nouveau <code>data.frame</code>, nommée <code>pi</code>, correspond à la proportion de l’effectif total échantillonné, contenu dans chaque cohorte. Puisque nous n’avons rien spécifié, <code>mixparam()</code> suppose que chaque cohorte contient une proportion identiques des individus de la population, et fixe donc la proportion à 0.2 (soit 20% de l’abondance totale dans chacune des 5 cohortes supposées). Nous savons pertinemment que ces proportions sont fausses puisqu’en réalité, l’abondance au sein des cohortes décroit avec l’âge des individus en raison de la mortalité. On sait donc que la cohorte la plus jeune sera la plus abondante, et que les cohortes plus âgées seront de moins en moins abondantes. Ces proportions seront estimées automatiquement par la fonction <code>mix()</code> lorsque nous réaliserons la décomposition polymodale. Les autres colonnes de <code>param_01</code>, qui contiennent les valeurs que nous avons fournies manuellement, seront également ajustées lors de la décomposition polymodale</p>
</section>
<section id="ajustement-des-lois-normales-aux-données" class="level3 page-columns page-full" data-number="4.7.4">
<h3 data-number="4.7.4" class="anchored" data-anchor-id="ajustement-des-lois-normales-aux-données"><span class="header-section-number">4.7.4</span> Ajustement des lois Normales aux données</h3>
<p>Maintenant que nous disposons des deux objets nécessaires, nous pouvons réaliser la décomposition polymodale qui consiste, grâce à la fonction <code>mix()</code>, à ajuster une distribution Normale à chaque cohorte supposée de la population échantillonnés.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>res_01 <span class="ot">&lt;-</span> <span class="fu">mix</span>(mix_01, param_01)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in mix(mix_01, param_01): The optimization process terminated because
iteration limit exceeded</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>res_01</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Parameters:
       pi     mu sigma
1 0.46418  3.903 1.086
2 0.27062  8.795 1.555
3 0.14355 18.115 2.102
4 0.09100 28.231 2.861
5 0.03066 35.021 2.344

Distribution:
[1] "norm"

Constraints:
   conpi    conmu consigma 
  "NONE"   "NONE"   "NONE" </code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>mix()</code> : réalise la décomposition polymodale. La fonction identifie une combinaison de distributions Normales qui s’ajuste le mieux possible aux données observées compte tenu des données brutes et des caractéristiques approximatives de chaque distribution Normale fournie par l’utilisateur.</p>
</div></div><p>La fonction <code>mix()</code> peut produire quelques avertissements. Ignorez-les à ce stade : seuls les messages d’erreurs sont problématiques et nous y reviendrons plus tard. L’objet <code>res_01</code> contient donc les résultats de la décomposition polymodale. C’est une liste de 3 éléments dont seul le premier nous intéresse.^[Il s’appelle <code>parameters</code>, sans majuscule, même si <code>R</code> affiche son nom avec une majuscule. Vous pouvez le vérifier en tapant <code>str(res_01)</code>.</p>
<p><code>str()</code> : affiche la <strong>str</strong>ucture interne d’objets complexes.] Il contient les valeurs ajustées pour les 3 paramètres des distributions Normales (<code>pi</code>, <code>mu</code> et <code>sigma</code>) pour chacune des 5 cohortes identifiées en mars 2010.</p>
<p>Ainsi, par exemple, pour l’échantillon de mars 2010, la première ligne du tableau <code>parameters</code> contenu dans <code>res_01</code> nous apprend les choses suivantes :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>res_01<span class="sc">$</span>parameters</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          pi        mu    sigma
1 0.46417551  3.903201 1.085989
2 0.27061611  8.795297 1.555004
3 0.14354832 18.114948 2.101807
4 0.09099874 28.230516 2.861214
5 0.03066132 35.020985 2.343520</code></pre>
</div>
</div>
<ul>
<li>La première cohorte représente 46.42% de l’abondance totale de la population</li>
<li>La taille moyenne des individus composant cette cohorte vaut 3.9 millimètres</li>
<li>L’écart-type (ou polymorphisme de taille) de cette cohorte vaut 1.1 millimètres</li>
</ul>
<p>Les distributions Normales qui ont été ajustées peuvent être visualisées grâce à la fonction <code>plot()</code> :</p>
<div class="cell page-columns page-full">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(res_01)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display page-columns page-full">
<div id="fig-ajustement" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="04-Cohortes_files/figure-html/fig-ajustement-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption margin-caption">Figure&nbsp;4.5: Distribution observée (histogramme bleu) et cohortes ajustées (courbes rouges). Les triangles indiquent la position du mode des cohortes et la courbe verte est la somme de toutes les distributions Normales. Idéallement, cette courbe devrait être étroitement ajustée aux données observées</figcaption>
</figure>
</div>
</div>
</div>
<p>On observe sur la <a href="#fig-ajustement">Figure&nbsp;<span class="quarto-unresolved-ref">fig-ajustement</span></a> et dans l’objet <code>res_01$parameters</code> que la qualité de l’ajustement (et donc de la décomposition polymodale) est bonne :</p>
<ul>
<li>la courbe verte représente bien les données observées : elle est bien ajustée aux contours de l’histogramme.</li>
<li>l’abondance des cohortes décroit avec l’âge de la cohorte : <code>pi</code> décroit de la cohorte la plus jeune à la cohorte la plus âgée.</li>
<li>la taille moyenne des individus augmente avec l’âge de la cohorte : <code>mu</code> augmente de la cohorte la plus jeune à la cohorte la plus âgée.</li>
<li>le polymorphisme (ou dispersion des tailles autour de la moyenne) augmente avec l’âge de la cohorte : <code>sigma</code> augmente de la cohorte la plus jeune à la cohorte la plus âgée.</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
De l’importance du choix des valeurs initiales
</div>
</div>
<div class="callout-body-container callout-body">
<p>Si nous avions choisi d’autres valeurs approchée lors de la création de l’objet <code>param_01</code> avec la fonction <code>mixparam()</code>, l’ajustement obtenu aurait pu être différent. La décomposition polymodale n’est pas une science exacte et il est souvent nécessaire de procéder par tâtonnements pour trouver des valeurs satisfaisantes. En particulier, les résultats que nous obtenons dépendent :</p>
<ul>
<li>du choix des valeurs pour la fonction <code>mixparam()</code></li>
<li>du choix des classes de tailles pour la structure démographique instantanée. Ici, nous avons des classes de tailles de un millimètre de large, mais nous aurions pu faire un autre choix (1,5 millimètre de large, ou 2) et nous aurions alors obtenu des résultats différents.</li>
</ul>
<p>Il est donc important de retenir que les résultats obtenus ne sont pas “justes” ou “faux” en tant que tel et qu’il n’y a pas qu’une seule “bonne réponse”. La qualité des résultats obtenus s’apprécie au regard de ce qu’on connait de l’espèce étudiée (traits d’histoire de vie, période de reproduction et de recrutement, nombre de cohorte supposées selon la date, etc.), et de ce qu’on connait du comportement “normal” des cohortes (baisse de l’abondance avec l’âge, augmentation de la taille moyenne avec l’âge, augmentation du polymorphisme avec l’âge).</p>
</div>
</div>
</section>
<section id="et-en-cas-de-message-derreur" class="level3 page-columns page-full" data-number="4.7.5">
<h3 data-number="4.7.5" class="anchored" data-anchor-id="et-en-cas-de-message-derreur"><span class="header-section-number">4.7.5</span> Et en cas de message d’erreur ?</h3>
<p>Lorsque vous utiliserez la fonction <code>mix()</code>, il se peut que des messages d’erreurs et/ou des messages d’avertissement apparaissent.</p>
<ul class="fa-ul">
<li>
<span class="fa-li" style="color:CornFlowerBlue"><i class="fa-solid fa-info-circle" aria-hidden="true"></i></span> Les messages d’information et les avertissements commencent en général par le mot <code>Warning</code> et sont presque toujours sans conséquence. La commande a été comprise par <code>RStudio</code> et un résultat a été produit. Dans le cas de la fonction <code>mix()</code>, les avertissements indiquent que la solution trouvée (l’ajustement des loi Normales aux cohortes observées) n’est peut-être pas optimale, mais une solution a néanmoins été obtenue.
</li>
<li>
<p><span class="fa-li" style="color:Crimson"><i class="fa-solid fa-bomb" aria-hidden="true"></i></span> Les messages d’erreurs commencent par <code>Erreur</code> ou <code>Error</code> et indiquent que la commande n’a pas abouti. Dans le cas de la fonction <code>mix()</code>, cela peut être lié à 2 choses :</p>
<ol type="1">
<li>soit les valeurs choisies pour la fonction <code>mixparam()</code> sont trop éloignées de la position des pics réels, et la fonction <code>mix()</code> ne parvient donc pas à trouver de solution satisfaisante</li>
<li>soit le nombre de valeurs choisies pour la fonction <code>mixparam()</code> n’est pas le bon. Par exemple, s’il y a 5 cohortes et qu’on ne fournit que 4 valeurs pour <code>mu</code> et <code>sigma</code>, un message d’erreur apparaîtra. De même, s’il y a 4 cohortes et qu’on fournit 5 valeurs pour <code>mu</code> et <code>sigma</code>, un message d’erreur apparaîtra. Enfin, si on ne fournit pas le même nombre de valeurs pour <code>mu</code> et pour <code>sigma</code>, un message d’erreur apparaîtra.
</li>
</ol></li></ul>

<p>Dans les deux cas, vous devez</p>
<ol type="1">
<li>revenir à votre structure démographique instantanée et l’observer plus attentivement</li>
<li>déterminer des valeurs plus appropriées<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> pour la fonction <code>mixparam()</code></li>
<li>ré-exécuter le code depuis la création de l’objet <code>param_01</code> et jusqu’à la décomposition polymodale avec la fonction <code>mix()</code></li>
</ol>
<div class="no-row-height column-margin column-container"><li id="fn1"><p><sup>1</sup>&nbsp;ajoutez ou retirez une cohorte si besoin, et choisissez des valeurs plus proches des pics observés</p></li></div></section>
</section>
<section id="taille-moyenne-et-abondance-des-cohortes" class="level2 page-columns page-full" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="taille-moyenne-et-abondance-des-cohortes"><span class="header-section-number">4.8</span> Taille moyenne et abondance des cohortes</h2>
<p>À partir des résultats de la décomposition polymodale, nous devons maintenant calculer l’abondance (<em>i.e.</em> le nombre d’individus) de chaque cohorte. Nous devrons ensuite stocker dans un nouveau tableau :</p>
<ol type="1">
<li>la date d’échantillonnage (mars 2010)</li>
<li>la valeur d’abondance de la cohorte dont on souhaite réaliser le suivi (il s’agit de la cohorte la plus jeune en mars 2010)</li>
<li>la taille moyenne des individus de la cohorte dont on souhaite réaliser le suivi<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></li>
</ol>
<div class="no-row-height column-margin column-container"><li id="fn2"><p><sup>2</sup>&nbsp;on sait déjà que cette taille vaut 3.9 millimètres en mars 2010.</p></li></div><p>L’abondance d’une cohorte est obtenue en multipliant la valeur de <code>pi</code> de la cohorte d’intérêt par le nombre total d’individus échantillonnés en mars 2010. En effet, sur la <a href="#fig-ajustement">Figure&nbsp;<span class="quarto-unresolved-ref">fig-ajustement</span></a>, la surface totale comprise entre l’axe des abscisses et la courbe verte vaut 1. Cette surface correspond au nombre total d’individus échantillonnés en mars 2010 :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(Nas_01)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 468</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>nrow()</code> : affiche le nombre de lignes d’une matrice ou d’un <code>data.frame</code></p>
</div></div><div class="page-columns page-full"><p>Puisque la première cohorte représente 46.42% de l’abondance totale<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>, tout ce dont on a besoin pour connaitre l’abondance de la cohorte la plus jeune est :</p><div class="no-row-height column-margin column-container"><li id="fn3"><p><sup>3</sup>&nbsp;c’est ce que nous dit la valeur de <code>pi</code> de la première cohorte dans le tableau <code>res_01$parameters</code> :</p></li></div></div>
<div class="cell page-columns page-full">

<div class="no-row-height column-margin column-container"><div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">pi</th>
<th style="text-align: right;">mu</th>
<th style="text-align: right;">sigma</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.4642</td>
<td style="text-align: right;">3.9032</td>
<td style="text-align: right;">1.0860</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.2706</td>
<td style="text-align: right;">8.7953</td>
<td style="text-align: right;">1.5550</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.1435</td>
<td style="text-align: right;">18.1149</td>
<td style="text-align: right;">2.1018</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.0910</td>
<td style="text-align: right;">28.2305</td>
<td style="text-align: right;">2.8612</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.0307</td>
<td style="text-align: right;">35.0210</td>
<td style="text-align: right;">2.3435</td>
</tr>
</tbody>
</table>
</div></div></div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>res_01<span class="sc">$</span>parameters[<span class="dv">1</span>, <span class="dv">1</span>] <span class="sc">*</span> <span class="fu">nrow</span>(Nas_01)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 217.2341</code></pre>
</div>
</div>
<p>En arrondissant à l’entier le plus proche, on obtient :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(res_01<span class="sc">$</span>parameters[<span class="dv">1</span>, <span class="dv">1</span>] <span class="sc">*</span> <span class="fu">nrow</span>(Nas_01), <span class="dv">0</span>)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 217</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>round()</code> : arrondit des valeurs numériques. Le deuxième argument permet d’indiquer le nombre de décimales.</p>
</div></div><p>Nous savons donc maintenant que la première cohorte, la plus jeune de la population échantillonnée en mars 2010, a donc une taille moyenne de 3.9 millimètre et une abondance de 217 individus. Nous allons maintenant utiliser ces valeurs pour créer un tableau et placer le premier point des courbes de croissance, de survie et d’Allen.</p>
</section>
<section id="tableau-et-mise-en-forme-des-données" class="level2 page-columns page-full" data-number="4.9">
<h2 data-number="4.9" class="anchored" data-anchor-id="tableau-et-mise-en-forme-des-données"><span class="header-section-number">4.9</span> Tableau et mise en forme des données</h2>
<p>Nous venons de décrire ci-dessus la méthode que vous devrez appliquer pour chaque date d’échantillonnage. En suivant les mêmes étapes, vous devriez être en mesure d’obtenir la taille et l’abondance moyennes de notre cohorte d’intérêt pour les 9 dates restantes. Lorsque vous effectuerez la décomposition polymodale pour ces 9 dates, n’oubliez jamais que vous voulez suivre <em>systématiquement la même cohorte dans le temps</em>. Cette cohorte va progressivement évoluer vers des tailles plus importantes puisque les individus grandissent chaque mois et chaque année. Notre cohorte d’intérêt va donc progressivement se décaler vers la droite des structures démographiques instantanées, et les informations de cette cohortes ne seront donc pas systématiquement situées sur la première ligne des résultats de la décomposition polymodale.</p>
<p>Pour chaque date, on s’attend donc à ce que la taille moyenne des individus soit plus grande que la taille obtenue pour la date d’échantillonnage précédente. De même, l’abondance devrait diminuer au fil du temps en raison de la mortalité naturelle qui affecte tous les individus de la population.</p>
<p>Pour produire les 3 courbes (croissance, survie et Allen) dont nous avons besoin, nous allons créer un <code>tibble</code> contenant 3 colonnes :</p>
<ol type="1">
<li>la date d’échantillonnage</li>
<li>la taille moyenne des individus de la cohorte en millimètres</li>
<li>l’abondance de la cohorte (nombre d’individus de la cohorte)</li>
</ol>
<p>Nous pouvons utiliser la fonction <code>tribble()</code> pour le faire :</p>
<div class="cell column-page-right">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>cohort <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>date,        <span class="sc">~</span>size,                  <span class="sc">~</span>abundance,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"2010-03-01"</span>, res_01<span class="sc">$</span>parameters[<span class="dv">1</span>,<span class="dv">2</span>], res_01<span class="sc">$</span>parameters[<span class="dv">1</span>,<span class="dv">1</span>] <span class="sc">*</span> <span class="fu">nrow</span>(Nas_01)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>tribble()</code> : permet de créer un <code>tibble</code> ligne par ligne. Le “r” de <code>tribble</code> est l’abréviation de “<strong>r</strong>ow”.</p>
</div></div><p>Pour chaque nouvelle date d’échantillonnage, vous devrez compléter ce tableau en ajoutant une nouvelle ligne à l’intérieur de cette fonction <code>tribble()</code>.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Attention !
</div>
</div>
<div class="callout-body-container callout-body">
<p>Une erreur fréquente est de saisir les données obtenues à chaque date d’échantillonnage dans un tableau différent à chaque fois. Ça n’est pas ce qu’il faut faire ! Il faut au contraire compléter le tableau <code>cohorte</code> en ajoutant une nouvelle ligne au tableau existant de la façon suivante :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>cohort <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>date,        <span class="sc">~</span>size,                  <span class="sc">~</span>abundance,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"2010-03-01"</span>, res_01<span class="sc">$</span>parameters[<span class="dv">1</span>,<span class="dv">2</span>], res_01<span class="sc">$</span>parameters[<span class="dv">1</span>,<span class="dv">1</span>] <span class="sc">*</span> <span class="fu">nrow</span>(Nas_01),</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"2010-09-01"</span>, ...                   , ...</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<p>Nous devons spécifier une dernière chose afin de produire les graphiques : à ce stade, la colonne <code>date</code> du nouveau tableau <code>cohort</code> est considéré comme une variable de type <code>character</code> (type <code>&lt;chr&gt;</code>) :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>cohort</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  date        size abundance
  &lt;chr&gt;      &lt;dbl&gt;     &lt;dbl&gt;
1 2010-03-01  3.90      217.</code></pre>
</div>
</div>
<p>Il nous faut donc la transformer pour que <code>R</code> la reconnaisse comme étant une variable temporelle afin que les données apparaissent dans l’ordre chronologique (et non alphabétique) sur l’axe des abscisses de nos graphiques. Voilà comment procéder :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># On charge le package lubridate pour travailler avec des dates</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Ce package fait partie du tidyverse</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Si vous l'avez installé, lubridate est disponible sur votre ordinateur</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>cohort <span class="ot">&lt;-</span> cohort <span class="sc">%&gt;%</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">date</span>(date))</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>mutate()</code> : crée de nouvelles variables dans un <code>tibble</code>, ou modifie des variables existantes.<br>
<br> <code>date()</code> : transforme des variables de type <code>&lt;chr&gt;</code> (caractères) en variable de type <code>&lt;date&gt;</code> (dates).</p>
</div></div><p>On vérifie que la variable <code>date</code> possède maintenant le type <code>&lt;date&gt;</code> :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>cohort</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  date        size abundance
  &lt;date&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 2010-03-01  3.90      217.</code></pre>
</div>
</div>
<p>À ce stade, nous avons tout ce qu’il nous faut pour produire les courbes de croissance, de survie et d’Allen, à l’aide de <code>ggplot2</code>. Évidemment, chaque courbe ne contiendra ici qu’un seul point puisque nous avons examiné pour l’instant qu’une seule date d’échantillonnage. Elles ne seront complètes que lorsque que vous aurez répété ce travail pour l’ensemble des 10 dates d’échantillonnage.</p>
</section>
<section id="courbe-de-croissance" class="level2 page-columns page-full" data-number="4.10">
<h2 data-number="4.10" class="anchored" data-anchor-id="courbe-de-croissance"><span class="header-section-number">4.10</span> Courbe de croissance</h2>
<p>On place les dates d’échantillonnage sur l’axe des abscisses, et la taille moyennes des individus de la cohorte d’intérêt sur l’axe des ordonnées :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>cohort <span class="sc">%&gt;%</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> size, <span class="at">group =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Date d'échantillonnage"</span>,</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Longueur moyenne de la coquille (mm)"</span>,</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Courbe de croissance"</span>) <span class="sc">+</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>geom_point()</code> et <code>geom_line()</code> : permettent d’ajouter des points et des lignes (respectivement) sur un graphique<br>
<br> <code>labs()</code> : permet de spécifier le titre d’un graphique et de ses axes<br>
<br> <code>theme_bw()</code> : change l’apparence générale du graphique</p>
</div></div><div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="fig-croiss" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="04-Cohortes_files/figure-html/fig-croiss-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption margin-caption">Figure&nbsp;4.6: Courbe de croissance d’une cohorte de la population de <em>Nassarius reticulatus</em>, suivie pendant 5 ans. À compléter avec les données des 9 autres dates d’échantillonnage</figcaption>
</figure>
</div>
</div>
</div>
<p>L’argument <code>group = 1</code> est utilisé pour indiquer que toutes les dates d’échantillonnage appartiennent à la même série temporelle, et qu’on souhaite donc relier les dates par une ligne. Le résultat sera nettement plus parlant quand vous aurez ajouté des données d’autres dates d’échantillonnage sur le graphique, afin de visualiser l’évolution de la taille moyenne des individus de la cohorte d’intérêt au fil du temps.</p>
</section>
<section id="courbe-de-survie" class="level2 page-columns page-full" data-number="4.11">
<h2 data-number="4.11" class="anchored" data-anchor-id="courbe-de-survie"><span class="header-section-number">4.11</span> Courbe de survie</h2>
<p>Pour produire la courbe de survie, on procède de la même façon, mais on place les dates d’échantillonnage sur l’axe des abscisses, et l’abondance de la cohorte d’intérêt sur l’axe des ordonnées :</p>
<div class="cell page-columns page-full">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>cohort <span class="sc">%&gt;%</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> abundance, <span class="at">group =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Date d'échantillonnage"</span>,</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Abondance de la cohorte"</span>,</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Courbe de survie"</span>) <span class="sc">+</span></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display page-columns page-full">
<div id="fig-survie" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="04-Cohortes_files/figure-html/fig-survie-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption margin-caption">Figure&nbsp;4.7: Courbe de survie d’une cohorte de la population de <em>Nassarius reticulatus</em>, suivie pendant 5 ans. À compléter avec les données des 9 autres dates d’échantillonnage</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="courbe-dallen" class="level2 page-columns page-full" data-number="4.12">
<h2 data-number="4.12" class="anchored" data-anchor-id="courbe-dallen"><span class="header-section-number">4.12</span> Courbe d’Allen</h2>
<p>Pour produire la courbe de survie, on place la taille moyenne des individus de la cohorte sur l’axe des abscisses, et l’abondance de la cohorte d’intérêt sur l’axe des ordonnées :</p>
<div class="cell page-columns page-full">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>cohort <span class="sc">%&gt;%</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> size, <span class="at">y =</span> abundance, <span class="at">group =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Longueur moyenne de la coquille (mm)"</span>,</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Abondance de la cohorte"</span>,</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Courbe d'Allen"</span>) <span class="sc">+</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display page-columns page-full">
<div id="fig-allen" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="04-Cohortes_files/figure-html/fig-allen-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption margin-caption">Figure&nbsp;4.8: Courbe d’Allen d’une cohorte de la population de <em>Nassarius reticulatus</em>, suivie pendant 5 ans. À compléter avec les données des 9 autres dates d’échantillonnage</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="relation-allométrique" class="level2 page-columns page-full" data-number="4.13">
<h2 data-number="4.13" class="anchored" data-anchor-id="relation-allométrique"><span class="header-section-number">4.13</span> Relation allométrique</h2>
<p>L’un des objectifs de ce travail était de produire une courbe d’Allen pour étudier les <strong>variations de biomasses</strong>. Pour y parvenir, nous devons faire une courbe d’Allen sur laquelle figure la masse moyenne des individus de la cohorte d’intérêt (en grammes), plutôt que la taille moyenne des individus de cette cohorte (en millimètres). Pour passer des tailles en millimètres aux masses en grammes, il nous suffit d’appliquer la relation allométrique fournie dans la <a href="#sec-pres"><span class="quarto-unresolved-ref">sec-pres</span></a>, et d’ajouter une nouvelle colonne à notre tableau grâce à la fonction <code>mutate()</code> :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>cohort_2 <span class="ot">&lt;-</span> cohort <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">weight =</span> <span class="fl">0.0013</span> <span class="sc">*</span> size <span class="sc">^</span> <span class="fl">2.3</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>cohort_2</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  date        size abundance weight
  &lt;date&gt;     &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;
1 2010-03-01  3.90      217. 0.0298</code></pre>
</div>
</div>
<p>Il n’y a plus qu’à utiliser cette nouvelle variable sur l’axe des abscisses d’une courbe d’Allen :</p>
<div class="cell page-columns page-full">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>cohort_2 <span class="sc">%&gt;%</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> weight, <span class="at">y =</span> abundance, <span class="at">group =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Masse moyenne des individus (g)"</span>,</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Abondance de la cohorte"</span>,</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Courbe d'Allen"</span>) <span class="sc">+</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display page-columns page-full">
<div id="fig-biomasse" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="04-Cohortes_files/figure-html/fig-biomasse-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption margin-caption">Figure&nbsp;4.9: Courbe d’Allen d’une cohorte de la population de <em>Nassarius reticulatus</em>, suivie pendant 5 ans. À compléter avec les données des 9 autres dates d’échantillonnage</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="à-vous-de-jouer" class="level2 page-columns page-full" data-number="4.14">
<h2 data-number="4.14" class="anchored" data-anchor-id="à-vous-de-jouer"><span class="header-section-number">4.14</span> À vous de jouer !</h2>
<p>Au final, voilà comment on peut résumer les différentes étapes de ce travail.</p>
<div class="column-page-right">
<p><img src="images/diagram.png" class="img-fluid"></p>
</div>
<p>Assurez vous que vous avez bien compris chaque étape de la méthode décrite pour l’échantillonnage de mars 2010, et pourquoi on fait les choses présentées ici dans l’ordre où on les fait. À ce stade, vous devriez déjà avoir un script assez long qui devrait contenir la plupart des commandes évoquées plus haut. Vous devriez donc pouvoir reproduire ces étapes pour toutes les autres dates d’échantillonnage en faisant des copier-coller et en modifiant quelques éléments précis (dates, nom des objets, valeurs de tailles moyennes pour les cohortes, etc.). Attention aussi à adopter une structure de script la plus clair possible, afin de pouvoir corriger les éventuels bugs ou problèmes plus facilement.</p>
<p>Il ne vous reste donc plus qu’à reproduire ce travail pour les 9 autres dates d’échantillonnage afin (i) de récupérer les valeurs d’abondance, de taille et de masse moyenne des individus de la cohorte d’intérêt (celle qui a été recrutée en mars 2010) et (ii) de compléter les 3 courbes que nous avons commencées plus haut.</p>
<p>Bon courage !</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-R-mixdist" class="csl-entry" role="listitem">
Macdonald, Peter, et with contributions from Juan Du. 2018. <em>mixdist: Finite Mixture Distribution Models</em>. <a href="https://CRAN.R-project.org/package=mixdist">https://CRAN.R-project.org/package=mixdist</a>.
</div>
<div id="ref-tidyverse2019" class="csl-entry" role="listitem">
Wickham, Hadley, Mara Averick, Jennifer Bryan, Winston Chang, Lucy D’Agostino McGowan, Romain François, Garrett Grolemund, et al. 2019. <span>«&nbsp;Welcome to the <span>tidyverse</span>&nbsp;»</span>. <em>Journal of Open Source Software</em> 4 (43): 1686. <a href="https://doi.org/10.21105/joss.01686">https://doi.org/10.21105/joss.01686</a>.
</div>
</div>
</section>


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copié");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copié");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
          // default icon
          link.classList.add("external");
      }
    }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03-TwoSampleTests.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Comparaison de moyennes : deux échantillons indépendants</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-DynamicSystems.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Systèmes dynamiques</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>